# 开发环境配置
server:
  # 服务器的HTTP端口，默认为9310
  port: 9310
  servlet:
    # 应用的访问路径
    context-path: /
file-server:
  minio:
    # minio地址
    endpoint: http://47.119.125.3:9000
    # minio 账号
    accesskey: minio
    # minio 密码
    secretKey: minio123
    # 存储的bucket名称，服务启动自动创建
    bucketName: test
    # 预览过期时间，默认60分钟
    expiry: 120